'use strict';
var Alexa = require('alexa-sdk');

var APP_ID = "amzn1.ask.skill.3bcc3809-e574-4304-b169-a5affade5d19";
var SKILL_NAME = 'Crazy State Laws';

/**
 * Array containing state law facts.
 */
var FACTS = [
    "In Utah, it is illegal to hire trombone players to play on the street to advertise an auction.",
    "In Utah, it is illegal to fish while on horseback.",
    "In Utah, it is illegal to hunt whales.",
    "In Utah, it is illegal not to drink milk.",
    "In Utah it’s legal for restaurants to serve wine with meals, but only if you ask for the wine list.",
    "In Utah, no one may have sex in the back of an ambulance if it is responding to an emergency call.",
    "In Utah, it is illegal to detonate any nuclear weapon.",
    "In Utah, birds have the right of way on all highways.",
    "In Utah, a husband is responsible for every criminal act committed by his wife while she is in his presence.",
    "In Utah, you’re not allowed to sell beverages containing more than 3% alcohol.",
    "In Utah, it is a felony to persistently tread on the cracks between paving stones on the sidewalk of a state highway.",
    "In Utah, during an emergency, alcohol may not be sold.",
    "In Utah, individuals may not possess beer in containers larger than two liters unless they are a retailer.",
    "In Utah, boxing matches that allow biting are not allowed.",
    "In Utah, it is illegal to cause a catastrophe.",
    "In Alabama, bear wrestling matches are prohibited.",
    "In Alabama, incestuous marriages are legal.",
    "In Alabama, it is illegal to impersonate a person of the clergy.",
    "In Alabama, it is illegal to maim oneself to escape duty.",
    "In Alabama, you may not have an ice cream cone in your back pocket at any time.",
    "In Alabama, masks may not be worn in public.",
    "In Alabama, it is considered an offense to open an umbrella on a street, for fear of spooking horses.",
    "In Alabama, women are able to retain all property they owned prior to marriage in the case of divorce. However, this provision does not apply to men.",
    "In Alabama, it is illegal to sell peanuts in Lee County after sundown on Wednesday.",
    "In Alabama, it is illegal for a driver to be blindfolded while operating a vehicle.",
    "In Alabama, dominoes may not be played on Sunday.",
    "In Alabama, it is illegal to wear a fake moustache that causes laughter in church.",
    "In Alabama, putting salt on a railroad track may be punishable by death.",
    "In Alabama, boogers may not be flicked into the wind.",
    "In Alabama, it is legal to drive the wrong way down a one-way street if you have a lantern attached to the front of your automobile.",
    "In Alaska, moose may not be viewed from an airplane.",
    "In Alaska, waking a sleeping bear to take a photograph is prohibited.",
    "In Alaska, it is considered an offense to push a live moose out of a moving airplane.",
    "In Arizona, camel hunting is prohibited.",
    "In Arizona, no one can feed garbage to pigs without first obtaining a permit, which requires annual renewal.",
    "In Arizona, any misdemeanor committed while wearing a red mask is considered a felony.",
    "In Arizona, there is a possible 25 years in prison for cutting down a cactus.",
    "In Arizona, donkeys cannot sleep in bathtubs.",
    "In Arizona, it is illegal to manufacture imitation cocaine.",
    "In Arizona, it is unlawful to refuse a person a glass of water.",
    "In Arizona, when being attacked by a criminal or burglar, you may only protect yourself with the same weapon that the other person posseses.",
    "In Arkansas, a law provides that school teachers who bob their hair will not get a raise.",
    "In Arkansas, it’s strictly prohibited to pronounce “Arkansas” incorrectly.",
    "In Arkansas, a pinball machine can't give more than 25 free games to a player who continues to win.",
    "In Arkansas, a man can legally beat his wife, but not more than once a month.",
    "In Arkansas, alligators may not be kept in bathtubs.",
    "In California, it’s unlawful to let a dog pursue a bear or bobcat at any time.",
    "In California, a frog that dies during a frog-jumping contest can't be eaten.",
    "In California, you may only throw a frisbee at the beach in Los Angeles County, CA with the lifeguard’s permission.",
    "In California, sunshine is guaranteed to the masses.",
    "In California, it is a misdemeanor to shoot at any kind of game from a moving vehicle, unless the target is a whale.",
    "In California, women may not drive in a house coat.",
    "In California, animals are banned from mating publicly within 1,500 feet of a tavern, school, or place of worship.",
    "In California, bathhouses are against the law.",
    "In Colorado, one may not mutilate a rock in a state park.",
    "In Colorado, you have to get a permit to modify the weather.",
    "In Colorado, car dealers are not allowed to show cars on a Sunday.",
    "In Colorado, it is illegal to ride a horse while under the influence.",
    "In Connecticut, town records may not be kept where liquor is sold.",
    "In Connecticut, you can be stopped by the police for biking over 65 miles per hour.",
    "In Connecticut, in order for a pickle to officially be considered a pickle, it must bounce.",
    "In Connecticut, it is illegal to dispose of used razor blades.",
    "In Connecticut, it is illegal to discharge a firearm from a public highway.",
    "In Delaware, it is illegal to fly over any body of water, unless one is carrying sufficient supplies of food and drink.",
    "In Florida, the term “motor vehicle” was revised to exclude swamp buggies, deregulating the primary mode of transportation in the state.",
    "In Florida, the state constitution allows for pregnant pigs to not be confined in cages.",
    "In Florida, one may not commit any “unnatural acts” with another person.",
    "In Florida, unmarried couples may not commit “lewd acts” and live together in the same residence.",
    "In Florida, corrupting the public morals is defined as a nuisance, and is declared a misdemeanor offense.",
    "In Florida, doors of all public buildings must open outwards.",
    "In Florida, it is illegal to sell your children.",
    "In Florida, women may be fined for falling asleep under a hair dryer, as can the salon owner.",
    "In Florida, a special law prohibits unmarried women from parachuting on Sunday or she shall risk arrest, fine, and/or jailing.",
    "In Florida, you may not kiss your wife’s breasts.",
    "In Florida, if an elephant is left tied to a parking meter, the parking fee has to be paid just as it would for a vehicle.",
    "In Florida, penalty for horse theft is death by hanging.",
    "In Florida, it is illegal to sing in a public place while attired in a swimsuit.",
    "In Florida, men may not be seen publicly in any kind of strapless gown.",
    "In Florida, having sexual relations with a porcupine is illegal.",
    "In Florida, it is illegal to skateboard without a license.",
    "In Georgia, you cannot live on a boat for more than 30 days during the calendar year, even if just passing through the state",
    "In Georgia, it is illegal to use profanity in front of a dead body which lies in a funeral home or in a coroners office.",
    "In Georgia, members of the state assembly cannot be ticketed for speeding while the state assembly is in session.",
    "In Georgia, donkeys may not be kept in bathtubs.",
    "In Georgia, signs are required to be written in English.",
    "In Georgia, no one may carry an ice cream cone in their back pocket if it is Sunday.",
    "In Hawaii, you can ride in the bed of a pickup truck with no safety equipment but you will be fined for riding in the back of a passenger car without a seatbelt.",
    "In Hawaii, you may only have one alcoholic drink in front of you at a time.",
    "In Hawaii, billboards are outlawed.",
    "In Hawaii, all residents may be fined as a result of not owning a boat.",
    "In Hawaii, coins are not allowed to be placed in one’s ears.",
    "In Idaho, it is illegal for a man to give his sweetheart a box of candy weighing less than fifty pounds.",
    "In Idaho, you may not fish on a camel’s back.",
    "In Idaho, riding a merry-go-round on Sundays is considered a crime.",
    "In Illinois, it is against the law to have sex with a corpse.",
    "In Illinois, it is illegal to hang “obstructions” form the rear view mirror, including fuzzy dice, air fresheners, GPS units, etc.",
    "In Illinois, you may be arrested for vagrancy if you do not have at least one dollar bill on your person.",
    "In Illinois, you must contact the police before entering the city in an automobile.",
    "In Indiana, hotel sheets must be exactly 99 inches long and 81 inches wide.",
    "In Indiana, liquor stores can't sell cooled water or soda, but they can sell uncooled soda.",
    "In Indiana, waitresses may not carry drinks into a restaurant or bar.",
    "In Indiana, anyone 14 or older who profanely curses, damns or swears by the name of God, Jesus Christ or the Holy Ghost, shall be fined one to three dollars for each offense, with a maximum fine of ten dollars per day.",
    "In Indiana, a three dollar fine per pack will be imposed on anyone playing cards under the Act for the Prevention of Gaming.",
    "In Indiana, the value of the mathematical term Pi is 3.",
    "In Indiana, one may not sniff glue.",
    "In Indiana, state government officials who engage in private duels can be dismissed from their post.",
    "In Indiana, a person must get a referral from a licensed physician if he or she wishes to see a hypnotist unless the desired procedure is to quit smoking or lose weight.",
    "In Indiana, smoking in the state legislature building is banned, except when the legislature is in session.",
    "In Indiana, all males 18 to 50 years old must work six days a year on public roads.",
    "In Indiana, baths may not be taken between the months of October and March.",
    "In Indiana, check forgery can be punished with public flogging up to 100 stripes.",
    "In Indiana, mustaches are illegal if the bearer has a tendency to habitually kiss other humans.",
    "In Indiana, it is illegal to sell cars on Sunday.",
    "In Indiana, pedestrians crossing the highway at night are prohibited from wearing tail lights.",
    "In Indiana, no one may catch a fish with his bare hands.",
    "In Iowa, it is a crime to use a dead person’s handicapped parking sign or license plate",
    "In Iowa, a man with a moustache may never kiss a woman in public.",
    "In Iowa, one-armed piano players must perform for free.",
    "In Iowa, kisses may last for no more than five minutes.",
    "In Iowa, tanning bed facilities must warn of the risk of getting a sunburn.",
    "In Iowa, all boxes used to pick hops must be exactly 36 inches long.",
    "In Kansas, rabbits may not be shot from motorboats.",
    "In Kansas, pedestrians crossing the highways at night must wear tail lights.",
    "In Kansas, the state game rule prohibits the use of mules to hunt ducks.",
    "In Kansas, if two trains meet on the same track, neither shall proceed until the other has passed.",
    "In Kentucky, one may not dye a duckling blue and offer it for sale unless more than six are for sale at once.",
    "In Kentucky, it is illegal to fish with a bow and arrow in Kentucky.",
    "In Louisiana, “fake” wrestling matches are prohibited.",
    "In Louisiana, spectators at a boxing match may not mock one of the contestants.",
    "In Louisiana, it is illegal to run an abortion advertisement.",
    "In Louisiana, it is illegal to steal an alligator.",
    "In Louisiana, it is specifically illegal to urinate in a city's water supply.",
    "In Louisiana, it is illegal to rob a bank and then shoot at the bank teller with a water pistol.",
    "In Louisiana, biting someone with your natural teeth is “simple assault,” while biting someone with your false teeth is “aggravated assault.",
    "In Louisiana, it is illegal to gargle in public places.",
    "In Louisiana, it is illegal to shoot lasers at police officers.",
    "In Louisiana, one may not “dare” another to go onto railroad tracks owned by another.",
    "In Louisiana, rituals that involve the ingestion of blood, urine, or fecal matter are not allowed.",
    "In Louisiana, rvery time a person is seriously burned, he must report the injury to the fire marshal.",
    "In Maine, shotguns are required to be taken to church in the event of a Native American attack.",
    "In Maine, you may not step out of a plane in flight.",
    "In Maine, you will be charged a fine for having your Christmas decorations still up after the 14th of January.",
    "In Maryland, thistles may not grow in one’s yard.",
    "In Massachusetts, it is illegal to give beer to hospital patients.",
    "In Massachusetts, candy may not contain more than 1% of alcohol.",
    "In Massachusetts, shooting ranges may not set up targets that resemble human beings.",
    "In Massachusetts, at a wake, mourners may eat no more than three sandwiches.",
    "In Massachusetts, tomatoes may not be used in the production of clam chowder.",
    "In Massachusetts, snoring is prohibited unless all bedroom windows are closed and securely locked.",
    "In Massachusetts, Quakers and witches are banned.",
    "In Massachusetts, an old ordinance declares goatees illegal unless you first pay a special license fee for the privilege of wearing one in public.",
    "In Massachusetts, bullets may not be used as currency.",
    "In Massachusetts, all men must carry a rifle to church on Sunday.",
    "In Massachusetts, alcoholic drink specials are illegal.",
    "In Massachusetts, hunting on Sundays is prohibited.",
    "In Massachusetts, public boxing matches are outlawed.",
    "In Massachusetts, it is illegal to go to bed without first having a full bath.",
    "In Massachusetts, no gorilla is allowed in the back seat of any car.",
    "In Michigan, persons may not be drunk on trains.",
    "In Michigan, it is illegal to kill a dog using a decompression chamber.",
    "In Michigan, no man may seduce and corrupt an unmarried girl, or else he risks five years in prison.",
    "In Michigan, a woman isn’t allowed to cut her own hair without her husband’s permission.",
    "In Minnesota, it is illegal to stand around any building without a good reason to be there.",
    "In Minnesota, a person may not cross state lines with a duck atop his head.",
    "In Minnesota, it is illegal to sleep naked.",
    "In Minnesota, any game in which participants attempt to capture a greased or oiled pig is illegal.",
    "In Minnesota, all men driving motorcycles must wear shirt",
    "In Minnesota, citizens may not enter Wisconsin with a chicken on their head.",
    "In Minnesota, all bathtubs must not have feet.",
    "In Mississippi, it is illegal to teach others what polygamy is.",
    "In Mississippi, a man may not seduce a woman by lying, and claiming he will marry her.",
    "In Mississippi, private citizens may personally arrest any person that disturbs a church service.",
    "In Mississippi, cattle rustling is punishable by hanging.",
    "In Mississippi, horses are not to be housed within 50 feet of any road.",
    "In Montana, one may not pretend to abuse an animal in the presence of a minor.",
    "In Montana, it is illegal for married women to go fishing alone on Sundays, and illegal for unmarried women to ever fish alone.",
    "In Montana, seven or more indians are considered a raiding or war party and it is legal to shoot them.",
    "In Montana, it is illegal to have a sheep in the cab of your truck without a chaperone.",
    "In Montana, it is a felony for a wife to open her husband’s mail.",
    "In Nebraska, it is illegal to fly a plane while drunk.",
    "In Nebraska, if a child burps during church, his parent may be arrested.",
    "In Nebraska, it is Illegal to go whale fishing.",
    "In Nebraska, it is illegal for bar owners to sell beer unless they are simultaneously brewing a kettle of soup.",
    "In Nebraska, it is illegal for a mother to give her daughter a perm without a state license.",
    "In Nevada, it is illegal to drive a camel on the highway.",
    "In Nevada, it’s still “legal” to hang someone for shooting your dog on your property.",
    "In New Hampshire, you may not tap your feet, nod your head, or in any way keep time to the music in a tavern, restaurant, or cafe.",
    "In New Hampshire, you cannot sell the clothes you are wearing to pay off a gambling debt.",
    "In New Hampshire, it is considered an offense to check into a hotel under an assumed name.",
    "In New Hampshire, it is illegal to pick seaweed up off of the beach.",
    "In New Hampshire, any cattle that crosses state roads must be fitted with a device to gather its feces.",
    "In New Hampshire, you may not run machinery on Sundays.",
    "In New Hampshire, on Sundays citizens may not relieve themselves while looking up.",
    "In New Jersey, all motorists must honk before passing another car, bicyclist, skater, and even a skateboarder.",
    "In New Jersey, it is illegal to wear a bullet-proof vest while committing a murder.",
    "In New Jersey, one must yield a phone line to a person if it is an emergency.",
    "In New Jersey, you cannot pump your own gas.",
    "In New Jersey, it is against the law for a man to knit during the fishing season.",
    "In New Jersey, it is against the law to “frown” at a police officer.",
    "In New Jersey, if you have been convicted of a DUI, you may never again apply for personalized license plates.",
    "In New Jersey, you may not slurp your soup.",
    "In New Jersey, automobiles are not to pass horse drawn carriages on the street.",
    "In New Jersey, it is illegal to delay or detain a homing pigeon.",
    "In New Mexico, idiots may not vote.",
    "In New York, it is illegal to congregate in public with two or more people while each wearing a mask or any face covering which disguises your identity.",
    "In New York, adultery is still a crime.",
    "In New York, it is against the law to throw a ball at someone’s head for fun.",
    "In New York, women may go topless in public, providing it is not being used as a business.",
    "In New York, citizens may not greet each other by “putting one’s thumb to the nose and wiggling the fingers”.",
    "In New York, a fine of $25 can be levied for flirting.",
    "In New York, slippers are not to be worn after 10:00 PM.",
    "In North Carolina, it is a felony to steal more than $1000 of grease.",
    "In North Carolina, it’s against the law to sing off key.",
    "In North Carolina, elephants may not be used to plow cotton fields.",
    "In North Carolina, a three dollar tax must be paid on all white goods sold.",
    "In North Carolina, organizations may not hold their meetings while the members present are in costume.",
    "In North Carolina, bingo games may not last over 5 hours unless it is held at a fair.",
    "In North Carolina, serving alcohol at a bingo game is not allowed.",
    "In North Dakota, it is illegal to lie down and fall asleep with your shoes on.",
    "In North Dakota, beer and pretzels can’t be served at the same time in any bar or restaurant.",
    "In Ohio, it is illegal for more than five women to live in a house.",
    "In Ohio, it is illegal to mistreat anything of great importance.",
    "In Ohio, no civil arrests may be made on Sunday or on the Fourth of July",
    "In Ohio, women are prohibited from wearing patent leather shoes in public.",
    "In Ohio, it is illegal to fish for whales on Sunday.",
    "In Ohio, it is illegal to get a fish drunk.",
    "In Ohio, participating or conducting a duel is prohibited.",
    "In Oklahoma, it is illegal for the owner of a bar to allow anyone inside to pretend to have sex with a buffalo.",
    "In Oklahoma, dogs must have a permit signed by the mayor in order to congregate in groups of three or more on private property.",
    "In Oklahoma, females are forbidden from doing their own hair without being licensed by the state.",
    "In Oklahoma, no one may spit on a sidewalk.",
    "In Oklahoma, it is against the law to read a comic book while operating a motor vehicle.",
    "In Oklahoma, it is illegal to wear your boots to bed.",
    "In Oklahoma, it is illegal to have the hind legs of farm animals in your boots.",
    "In Oklahoma, fish may not be contained in fishbowls while on a public bus.",
    "In Oklahoma, residents are taxed for the furniture in their homes, and any other personal belongings.",
    "In Oklahoma, tissues are not to be found in the back of one’s car.",
    "In Oklahoma, people who make “ugly faces” at dogs may be fined and/or jailed.",
    "In Oklahoma, cars must be tethered outside of public buildings.",
    "In Oregon, one may not test their physical endurance while driving a car on a highway.",
    "In Oregon, it is illegal to place a container filled with human fecal matter on the side of any highway.",
    "In Oregon, a door on a car may not be left open longer than is necessary.",
    "In Oregon, babies may not be carried on the running boards of a car.",
    "In Oregon, ice cream may not be eaten on Sundays.",
    "In Oregon, canned corn is not to be used as bait for fishing.",
    "In Oregon, dishes must drip dry.",
    "In Pennsylvania, it is against the law to discharge a gun, cannon, revolver or other explosive weapon at a wedding.",
    "In Pennsylvania, it is illegal to have over 16 women live in a house together because that constitutes a brothel.",
    "In Pennsylvania, it it illegal to sleep on top of a refrigerator outdoors.",
    "In Pennsylvania, you may not catch a fish by any body part except the mouth.",
    "In Pennsylvania, dynamite is not to be used to catch fish.",
    "In Pennsylvania, you may not sing in the bathtub.",
    "In Pennsylvania, fireworks stores may not sell fireworks to Pennsylvania residents.",
    "In Pennsylvania, ministers are forbidden from performing marriages when either the bride or groom is drunk.",
    "In Pennsylvania, any motorist who sights a team of horses coming toward him must pull well off the road, cover his car with a blanket or canvas that blends with the countryside, and let the horses pass.",
    "In Rhode Island, cap guns are illegal.",
    "In Rhode Island, ropes may not be strung across a highway.",
    "In Rhode Island, no one may bite off another's leg.",
    "In Rhode Island, any marriage where either of the parties is an idiot or lunatic is null and void.",
    "In Rhode Island, it is considered an offense to throw pickle juice on a trolley.",
    "In Rhode Island, riding a horse over any public highway for the purpose of racing, or testing the speed of the horse is illegal.",
    "In Rhode Island, professional sports, except ice polo and hockey, must obtain a license to play games on Sunday.",
    "In South Carolina, no work may be done on Sunday.",
    "In South Carolina, it is a capital offense to inadvertently kill someone while attempting suicide.",
    "In South Carolina, a person must be eighteen years old to play a pinball machine.",
    "In South Carolina, it is considered an offense to get a tattoo.",
    "In South Carolina, horses may not be kept in bathtubs.",
    "In South Carolina, by law, if a man promises to marry an unmarried woman, the marriage must take place.",
    "In South Carolina, a permit must be obtained to fire a missle.",
    "In South Carolina, musical instruments may not be sold on Sunday.",
    "In South Dakota, no horses are allowed into Fountain Inn unless they are wearing pants.",
    "In South Dakota, it is illegal to lie down and fall asleep in a cheese factory.",
    "In South Dakota, movies that show police officers being struck, beaten, or treated in an offensive manner are forbidden.",
    "In Tennessee, students may not hold hands while at school.",
    "In Tennessee, it is a crime to share your Netflix password.",
    "In Tennessee, any person who participates in a duel may not hold any public office in the state.",
    "In Tennessee, it is legal to gather and consume roadkill.",
    "In Tennessee, hollow logs may not be sold.",
    "In Tennessee, it is illegal to use a lasso to catch a fish.",
    "In Tennessee, “Crimes against nature” are prohibited.",
    "In Tennessee, interracial marriages are illegal.",
    "In Tennessee, it is illegal to place tacks on a highway.",
    "In Tennessee, it is illegal to dare a child to purchase a beer",
    "In Tennessee, skunks may not be carried into the state.",
    "In Texas, it is illegal to sell one’s eye.",
    "In Texas, it is illegal to milk another person’s cow.",
    "In Texas, it is illegal to take more than three sips of beer at a time while standing.",
    "In Texas, it is illegal for one to shoot a buffalo from the second story of a hotel.",
    "In Vermont, women must obtain written permission from their husbands to wear false teeth.",
    "In Virginia, children are not to go trick-or-treating on Halloween.",
    "In Virginia, it is illegal to tickle women.",
    "In Virginia, no animal may be hunted for on Sunday with the exception of raccoons, which may be hunted until 2:00 AM.",
    "In West Virginia, whistling underwater is prohibited.",
    "In West Virginia, it is illegal to snooze on a train.",
    "In West Virginia, for each act of public swearing a person shall be fined one dollar.",
    "In Washington, the harassing of Bigfoot, Sasquatch or other undiscovered subspecies is a felony punishable by a fine and/or imprisonment.",
    "In Washington, it is illegal to attach a vending machine to a utility pole without prior consent from the utility company.",
    "In Washington, destroying a beer cask or bottle of another is illegal.",
    "In Washington, X-rays may not be used to fit shoes.",
    "In Washington, all lollipops are banned.",
    "In Washington, it is illegal to pretend that one’s parents are rich.",
    "In Wisconsin, State Law made it illegal to serve apple pie in public restaurants without cheese.",
    "In Wisconsin, it is illegal to kiss on a train.",
    "In Wisconsin, it is illegal to cut a woman’s hair.",
    "In Wisconsin, margarine may not be substituted for butter in restaurants unless it is requested by the customer.",
    "In Wisconsin, butter substitutes are not allowed to be served in state prisons.",
    "In Wyoming, junk dealers may not make any business transactions with drunk persons.",
    "In Wyoming, using a firearm to fish is strictly forbidden.",
    "In Wyoming, it is illegal for women to stand within five feet of a bar while drinking.",
    "In Wyoming, you may not take a picture of a rabbit from January to April without an official permit."
];

exports.handler = function(event, context, callback) {
    var alexa = Alexa.handler(event, context);
    alexa.APP_ID = APP_ID;
    alexa.registerHandlers(handlers);
    alexa.execute();
};

var handlers = {
    'LaunchRequest': function () {
        this.emit('GetFact');
    },
    'GetNewFactIntent': function () {
        this.emit('GetFact');
    },
    'GetFact': function () {
        // Get a random space fact from the space facts list
        var factIndex = Math.floor(Math.random() * FACTS.length);
        var randomFact = FACTS[factIndex];

        // Create speech output
        var speechOutput = "Here's your state law: " + randomFact;

        this.emit(':tellWithCard', speechOutput, SKILL_NAME, randomFact)
    },
    'AMAZON.HelpIntent': function () {
        var speechOutput = "You can say tell me a state law, or, you can say exit... What can I help you with?";
        var reprompt = "What can I help you with?";
        this.emit(':ask', speechOutput, reprompt);
    },
    'AMAZON.CancelIntent': function () {
        this.emit(':tell', 'Goodbye!');
    },
    'AMAZON.StopIntent': function () {
        this.emit(':tell', 'Goodbye!');
    }
};
